// <auto-generated />
using System;
using Marilog.Infrastructure.DataAccess.ContextDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marilog.Infrastructure.Migrations
{
    [DbContext(typeof(MarilogContext))]
    [Migration("20260419070848_LayTimeEntities")]
    partial class LayTimeEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.CharterTerms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CargoQuantityMt")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("CharterTerms", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CargoQuantityMt")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LaytimeCommencedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LaytimeCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoyageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("IX_LaytimeCalculations_ContractId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("VoyageId")
                        .HasDatabaseName("IX_LaytimeCalculations_VoyageId");

                    b.HasIndex("VoyageId", "OperationType")
                        .HasDatabaseName("IX_LaytimeCalculations_Voyage_Operation");

                    b.ToTable("LaytimeCalculations", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Factor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaytimeCalculationId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedSofEventId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("LaytimeCalculationId")
                        .HasDatabaseName("IX_LaytimeExceptions_CalculationId");

                    b.ToTable("LaytimeExceptions", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Factor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImpactType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaytimeCalculationId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("LaytimeCalculationId")
                        .HasDatabaseName("IX_LaytimeSegments_CalculationId");

                    b.ToTable("LaytimeSegments", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.SofEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Factor")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImpactType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaytimeCalculationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("LaytimeCalculationId", "EventTime")
                        .HasDatabaseName("IX_SofEvents_Calculation_Time");

                    b.ToTable("SofEvents", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.AContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContractFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TypeId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DurationInMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyWage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("RankID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SignOffDate")
                        .HasColumnType("date");

                    b.Property<int?>("SignOffPort")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SignOnDate")
                        .HasColumnType("date");

                    b.Property<int?>("SignOnPort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VesselID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("PersonID");

                    b.HasIndex("RankID");

                    b.HasIndex("SignOffPort");

                    b.HasIndex("SignOnPort");

                    b.HasIndex("VesselID");

                    b.HasIndex("IsActive", "SignOffDate");

                    b.ToTable("CrewContracts", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewPayroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasComment("USD");

                    b.Property<decimal>("BasicWage")
                        .HasColumnType("decimal(12,2)")
                        .HasComment("USD");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Deductions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasComment("USD");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasComment("USD — BasicWage + Allowances - Deductions");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PayrollMonth")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("PayrollMonth");

                    b.HasIndex("Status");

                    b.HasIndex("ContractId", "PayrollMonth")
                        .IsUnique();

                    b.ToTable("CrewPayrolls", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewPayrollDisbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasComment("USD");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("CashOnBoard | CashAtOffice | BankTransfer");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("SwiftTransferId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VoyageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("Method");

                    b.HasIndex("OfficeId")
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.HasIndex("PayrollId");

                    b.HasIndex("Status");

                    b.HasIndex("SwiftTransferId")
                        .HasFilter("[SwiftTransferId] IS NOT NULL");

                    b.HasIndex("VoyageId")
                        .HasFilter("[VoyageId] IS NOT NULL");

                    b.ToTable("CrewPayrollDisbursements", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBaseCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("IsBaseCurrency")
                        .IsUnique()
                        .HasFilter("[IsBaseCurrency] = 1");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VesselId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DocNumber")
                        .IsUnique();

                    b.HasIndex("DocTypeId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("PortId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("VesselId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.DocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(14,4)");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(14,4)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_items", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("SentAt");

                    b.HasIndex("Status");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.EmailAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("EmailAttachments", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.EmailParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.HasIndex("Role");

                    b.HasIndex("ParticipantType", "ParticipantId");

                    b.ToTable("EmailParticipants", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.NavItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("NavItems", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Offices", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("SwiftTransferId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SwiftTransferId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BankSwiftCode")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Nationality")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PassportExpiry")
                        .HasColumnType("date");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeamanBookNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("Nationality");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("PortCode")
                        .IsUnique();

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("RankCode")
                        .IsUnique();

                    b.ToTable("Ranks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ranks_Department", "Department IN ('DECK', 'ENGINE', 'CATERING')");
                        });
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.SwiftTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverBank")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ReceiverCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("SenderBank")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SenderCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("SwiftReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ReceiverCompanyId");

                    b.HasIndex("SenderCompanyId");

                    b.HasIndex("SwiftReference")
                        .IsUnique();

                    b.HasIndex("TransactionDate");

                    b.ToTable("swift_transfers", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("FlagCountryID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrossTonnage")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IMONumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("FlagCountryID");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("IMONumber")
                        .IsUnique()
                        .HasFilter("[IMONumber] IS NOT NULL");

                    b.ToTable("Vessels", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Voyage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArrivalPortID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CargoQuantityMT")
                        .HasColumnType("decimal(14,3)");

                    b.Property<string>("CargoType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("CashOnBoard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CigarettesOnBoard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeparturePortID")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MasterContractID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PreviousMasterBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PLANNED");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VesselID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("VoyageMonth")
                        .HasColumnType("date");

                    b.Property<string>("VoyageNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalPortID");

                    b.HasIndex("DeparturePortID");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("MasterContractID");

                    b.HasIndex("Status");

                    b.HasIndex("VesselID");

                    b.HasIndex("VoyageMonth");

                    b.ToTable("Voyages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Voyages_Status", "Status IN ('PLANNED','UNDERWAY','COMPLETED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.VoyageStop", b =>
                {
                    b.Property<int>("StopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StopID"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PortID")
                        .HasColumnType("int");

                    b.Property<string>("PurposeOfCall")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<int>("VoyageID")
                        .HasColumnType("int");

                    b.HasKey("StopID");

                    b.HasIndex("PortID");

                    b.HasIndex("VoyageID", "StopOrder")
                        .IsUnique();

                    b.ToTable("VoyageStops", (string)null);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.CharterTerms", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.AContract", null)
                        .WithOne("CharterTerms")
                        .HasForeignKey("Marilog.Domain.Entities.LaytimeEntities.CharterTerms", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Marilog.Domain.ValueObjects.Laytime.LaytimeTerms", "LaytimeTerms", b1 =>
                        {
                            b1.Property<int>("CharterTermsId")
                                .HasColumnType("int");

                            b1.HasKey("CharterTermsId");

                            b1.ToTable("CharterTerms");

                            b1.WithOwner()
                                .HasForeignKey("CharterTermsId");

                            b1.OwnsOne("Marilog.Domain.ValueObjects.Laytime.DemurrageTerms", "Demurrage", b2 =>
                                {
                                    b2.Property<int>("LaytimeTermsCharterTermsId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("OnceOnDemurrageAlwaysOnDemurrage")
                                        .HasColumnType("bit")
                                        .HasColumnName("Demurrage_OnceAlwaysOnDemurrage");

                                    b2.Property<decimal>("RateUsdPerDay")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Demurrage_RateUsdPerDay");

                                    b2.HasKey("LaytimeTermsCharterTermsId");

                                    b2.ToTable("CharterTerms");

                                    b2.WithOwner()
                                        .HasForeignKey("LaytimeTermsCharterTermsId");
                                });

                            b1.OwnsOne("Marilog.Domain.ValueObjects.Laytime.DespatchTerms", "Despatch", b2 =>
                                {
                                    b2.Property<int>("LaytimeTermsCharterTermsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Basis")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("Despatch_Basis");

                                    b2.Property<decimal>("RateUsdPerDay")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Despatch_RateUsdPerDay");

                                    b2.HasKey("LaytimeTermsCharterTermsId");

                                    b2.ToTable("CharterTerms");

                                    b2.WithOwner()
                                        .HasForeignKey("LaytimeTermsCharterTermsId");
                                });

                            b1.OwnsOne("Marilog.Domain.ValueObjects.Laytime.LaytimeRuleOptions", "RuleOptions", b2 =>
                                {
                                    b2.Property<int>("LaytimeTermsCharterTermsId")
                                        .HasColumnType("int");

                                    b2.Property<bool>("AllowShiftingTime")
                                        .HasColumnType("bit")
                                        .HasColumnName("Rules_AllowShiftingTime");

                                    b2.Property<bool>("DraftSurveyCounts")
                                        .HasColumnType("bit")
                                        .HasColumnName("Rules_DraftSurveyCounts");

                                    b2.Property<bool>("HolidaysIncluded")
                                        .HasColumnType("bit")
                                        .HasColumnName("Rules_HolidaysIncluded");

                                    b2.Property<bool>("SundaysIncluded")
                                        .HasColumnType("bit")
                                        .HasColumnName("Rules_SundaysIncluded");

                                    b2.Property<bool>("TimeReversible")
                                        .HasColumnType("bit")
                                        .HasColumnName("Rules_TimeReversible");

                                    b2.HasKey("LaytimeTermsCharterTermsId");

                                    b2.ToTable("CharterTerms");

                                    b2.WithOwner()
                                        .HasForeignKey("LaytimeTermsCharterTermsId");
                                });

                            b1.OwnsOne("Marilog.Domain.ValueObjects.Laytime.CargoOperationTerms", "Discharging", b2 =>
                                {
                                    b2.Property<int>("LaytimeTermsCharterTermsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("CalendarType")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("Discharging_CalendarType");

                                    b2.Property<bool>("IsReversible")
                                        .HasColumnType("bit")
                                        .HasColumnName("Discharging_IsReversible");

                                    b2.Property<int>("NoticeHours")
                                        .HasColumnType("int")
                                        .HasColumnName("Discharging_NoticeHours");

                                    b2.Property<string>("OperationType")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("Discharging_OperationType");

                                    b2.Property<decimal>("RateMtPerDay")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("Discharging_RateMtPerDay");

                                    b2.HasKey("LaytimeTermsCharterTermsId");

                                    b2.ToTable("CharterTerms");

                                    b2.WithOwner()
                                        .HasForeignKey("LaytimeTermsCharterTermsId");
                                });

                            b1.OwnsOne("Marilog.Domain.ValueObjects.Laytime.CargoOperationTerms", "Loading", b2 =>
                                {
                                    b2.Property<int>("LaytimeTermsCharterTermsId")
                                        .HasColumnType("int");

                                    b2.Property<string>("CalendarType")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("Loading_CalendarType");

                                    b2.Property<bool>("IsReversible")
                                        .HasColumnType("bit")
                                        .HasColumnName("Loading_IsReversible");

                                    b2.Property<int>("NoticeHours")
                                        .HasColumnType("int")
                                        .HasColumnName("Loading_NoticeHours");

                                    b2.Property<string>("OperationType")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("Loading_OperationType");

                                    b2.Property<decimal>("RateMtPerDay")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("decimal(18,3)")
                                        .HasColumnName("Loading_RateMtPerDay");

                                    b2.HasKey("LaytimeTermsCharterTermsId");

                                    b2.ToTable("CharterTerms");

                                    b2.WithOwner()
                                        .HasForeignKey("LaytimeTermsCharterTermsId");
                                });

                            b1.Navigation("Demurrage")
                                .IsRequired();

                            b1.Navigation("Despatch");

                            b1.Navigation("Discharging");

                            b1.Navigation("Loading");

                            b1.Navigation("RuleOptions")
                                .IsRequired();
                        });

                    b.Navigation("LaytimeTerms")
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", b =>
                {
                    b.OwnsOne("Marilog.Domain.ValueObjects.Laytime.LaytimeResult", "Result", b1 =>
                        {
                            b1.Property<int>("LaytimeCalculationId")
                                .HasColumnType("int");

                            b1.Property<decimal>("AllowedDays")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Result_AllowedDays");

                            b1.Property<decimal>("BalanceDays")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Result_BalanceDays");

                            b1.Property<decimal>("DemurrageAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Result_DemurrageAmount");

                            b1.Property<decimal>("DespatchAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Result_DespatchAmount");

                            b1.Property<bool>("IsDemurrage")
                                .HasColumnType("bit")
                                .HasColumnName("Result_IsDemurrage");

                            b1.Property<decimal>("UsedDays")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Result_UsedDays");

                            b1.HasKey("LaytimeCalculationId");

                            b1.ToTable("LaytimeCalculations");

                            b1.WithOwner()
                                .HasForeignKey("LaytimeCalculationId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeException", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("LaytimeCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeSegment", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", null)
                        .WithMany("Segments")
                        .HasForeignKey("LaytimeCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.SofEvent", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", null)
                        .WithMany("SofEvents")
                        .HasForeignKey("LaytimeCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.AContract", b =>
                {
                    b.OwnsMany("Marilog.Domain.ValueObjects.Contract.ContractAmendment", "Amendments", b1 =>
                        {
                            b1.Property<int>("ContractId")
                                .HasColumnType("int");

                            b1.Property<int>("AmendmentNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("AmendmentNumber"));

                            b1.Property<string>("ChangedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<DateOnly>("EffectiveDate")
                                .HasColumnType("date");

                            b1.Property<DateTime>("RecordedAtUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("ContractId", "AmendmentNumber");

                            b1.HasIndex("ContractId");

                            b1.ToTable("ContractAmendments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsMany("Marilog.Domain.ValueObjects.Contract.ContractParty", "Parties", b1 =>
                        {
                            b1.Property<int>("ContractId")
                                .HasColumnType("int");

                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<string>("Role")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.HasKey("ContractId", "CompanyId", "Role");

                            b1.ToTable("ContractParties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("Amendments");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Company", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewContract", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Person", "Person")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "SignOffPortNav")
                        .WithMany()
                        .HasForeignKey("SignOffPort")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "SignOnPortNav")
                        .WithMany()
                        .HasForeignKey("SignOnPort")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Vessel", "Vessel")
                        .WithMany("CrewContracts")
                        .HasForeignKey("VesselID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Rank");

                    b.Navigation("SignOffPortNav");

                    b.Navigation("SignOnPortNav");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewPayroll", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.CrewContract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewPayrollDisbursement", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.CrewPayroll", null)
                        .WithMany("Disbursements")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.SwiftTransfer", "SwiftTransfer")
                        .WithMany()
                        .HasForeignKey("SwiftTransferId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Office");

                    b.Navigation("SwiftTransfer");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Document", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Company", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.DocumentType", "DocType")
                        .WithMany()
                        .HasForeignKey("DocTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Document", null)
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Company", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Buyer");

                    b.Navigation("Currency");

                    b.Navigation("DocType");

                    b.Navigation("Port");

                    b.Navigation("Supplier");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.DocumentItem", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Document", null)
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.EmailAttachment", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Email", null)
                        .WithMany("Attachments")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.EmailParticipant", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Email", null)
                        .WithMany("Participants")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.NavItem", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.NavItem", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Office", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Payment", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Document", null)
                        .WithMany("Payments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.SwiftTransfer", "SwiftTransfer")
                        .WithMany("Payments")
                        .HasForeignKey("SwiftTransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SwiftTransfer");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Person", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Country", "NationalityCountry")
                        .WithMany()
                        .HasForeignKey("Nationality")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NationalityCountry");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Port", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.SwiftTransfer", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Company", "ReceiverCompany")
                        .WithMany()
                        .HasForeignKey("ReceiverCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Company", "SenderCompany")
                        .WithMany()
                        .HasForeignKey("SenderCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("ReceiverCompany");

                    b.Navigation("SenderCompany");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Vessel", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Company", "Company")
                        .WithMany("Vessels")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Country", "FlagCountry")
                        .WithMany()
                        .HasForeignKey("FlagCountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("FlagCountry");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Voyage", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "ArrivalPort")
                        .WithMany()
                        .HasForeignKey("ArrivalPortID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "DeparturePort")
                        .WithMany()
                        .HasForeignKey("DeparturePortID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.CrewContract", "MasterContract")
                        .WithMany()
                        .HasForeignKey("MasterContractID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalPort");

                    b.Navigation("DeparturePort");

                    b.Navigation("MasterContract");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.VoyageStop", b =>
                {
                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Marilog.Domain.Entities.SystemEntities.Voyage", null)
                        .WithMany("Stops")
                        .HasForeignKey("VoyageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.LaytimeEntities.LaytimeCalculation", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Segments");

                    b.Navigation("SofEvents");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.AContract", b =>
                {
                    b.Navigation("CharterTerms");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Company", b =>
                {
                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.CrewPayroll", b =>
                {
                    b.Navigation("Disbursements");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Document", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Email", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.NavItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Person", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.SwiftTransfer", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Vessel", b =>
                {
                    b.Navigation("CrewContracts");
                });

            modelBuilder.Entity("Marilog.Domain.Entities.SystemEntities.Voyage", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
